### ISSUE TITLE
protobuf.decodeStr is not a function?

### ISSUE THREAD

**Issue by lazydino** [yangfch3/lordofpomelo#1]
Thanks for the effort. I at least can install and run the codebase with a little bit more work. After cloning the repos, I found I need to do 'apt-get install sysstat', and I also need to install a mime pacakge ( npm install mime@1.3.6 ) to fix the mime.lookup is not a function exception for express.

I am able to register and login, but chrome debugger stopped at build.js and complaining about "protobuf.decodeStr is not a function" Any idea?
![image](https://user-images.githubusercontent.com/1158846/34182774-80709f7a-e4cc-11e7-9576-161e07275fcd.png)

**Comment by lazydino** [comment]
Looks like I shouldn't rebuild the components, issuing "sh bin/component.sh" as the installation guide suggested produce a newer version of build.js that would cause the problem.

**Comment by yangfch3** [comment]
So sorry for the late reply! yes,  you shouldn't rebuild the components what will cover my fixed file.☺
