### ISSUE TITLE
非常感谢，终于可以跑起来了

### ISSUE THREAD

**Issue by hw233** [yangfch3/lordofpomelo#2]
非常感谢，终于可以跑起来了

**Comment by lazydino** [comment]
需要修改其他的设定吗？我的Pomelo服务器看来OK，但是无法跑游戏网页。您有这样的问题吗？

https://github.com/yangfch3/lordofpomelo/issues/1

我跑的是 node v7.9.0 on Ubuntu 16.04

**Comment by yangfch3** [comment]
^_^

**Comment by LeoCecilia** [comment]
想问一下你们的node版本是什么呢。。。总是抱path的错误

**Comment by yangfch3** [comment]
@LeoCecilia 6.x 版本的应该都没问题，我是在 6.9.x 下测试的

**Comment by lazydino** [comment]
Yes, I run 6.x too, and I am going to test it on the latest 8.9 Will let you know how it goes...
